---
title: "Beta Regression"
author: "Team Bee (Beta Regressionists) (Advisor: Dr. Seals)"
course: Capstone Projects in Data Science
bibliography: references.bib
csl: ieee.csl
format:
  revealjs:
    theme: dark
    embed-resources: true
    slide-number: false
    width: 1600
    height: 900
    df-print: paged
    html-math-method: katex
execute:
  echo: true
  warning: false
  message: false
  error: false
editor:
  markdown:
    wrap: 72
fig-align: center
---

## Introduction

Beta Regression: When the dependent variable is a ratio or percentage.

## Shortfalls of Normal Regression

- Assumes dependent variable is normally distributed
- Assumes variance is constant throughout

Generally not true with ratios or percentages

## When dependent variable lies in (0, 1)

- True of ratios or percents such as test scores
- Variance typically less near the extremes e.g 0 or 1.

## Reading Skills data set

- Reading skills based on IQ and if student has dyslexia N=44
- Normal regression shows IQ alone not significant in predicting reading score
- Beta regression shows IQ alone is significant in predicting reading score
[@smithson2006]

## Beta distribution

$$
f(y; \mu, \phi) = \frac{\Gamma(\phi)}{\Gamma(\mu \phi) \Gamma((1 - \mu)\phi)} y^{\mu\phi - 1}(1 - y)^{(1 - \mu)\phi - 1}, \quad 0 < y < 1
$$
Where:\
- **(μ)** is the mean, **(ϕ)** is the precision (inverse of the variance), **(Γ)** is the gamma function.

## Beta Distribution Variance

$$
\text{Var}(Y) = \frac{\mu(1 - \mu)}{1 + \phi}
$$
When $\mu$ is near the extremes, 0 or 1, variance drops. [@ferrari2004]

## References
